apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: pkg-gitops-simple-app
  annotations:
    kapp.k14s.io/change-rule.create-order: "upsert after upserting rbac"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting rbac"
spec:
  serviceAccountName: default-ns-sa
  syncPeriod: 1m
  fetch:
    - git:
        url: https://github.com/omocquais-p/kapp-demo.git
        ref: origin/master
        subPath: gitops
        path: gitops
    - git:
        url: https://github.com/omocquais-p/kapp-demo.git
        ref: origin/master
        subPath: gitops-values/dev
        path: values
  template:
    - ytt:
        paths:
          - values/
        valuesFrom:
          - path: values/values-ci.yml
  deploy:
    - kapp: {}