apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: pkg-gitops-example
  namespace: pkg-gitops
  annotations:
    kapp.k14s.io/change-rule.create-order: "upsert after upserting rbac"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting rbac"
spec:
  serviceAccountName: pkg-gitops-app-sa
  syncPeriod: 1m
  fetch:
    - git:
        url: https://github.com/omocquais-p/kapp-demo.git
        ref: origin/master
        subPath: packaging
  template:
    - ytt: {}

  deploy:
    - kapp: {}